# Version of docker compose syntax
version: "3.9"

# Main block
services:
  # name of our services
  app:
    build:
      context: .
      args:
        - DEV=true
    # 8000 to local machine to 8000 to our image
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # Command that uses the service to run
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # match the env data for the db
    environment:
    # name of the hostname as name of the db service
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # wait the db service to start before it starts the app service
    depends_on:
      - db

  # database service
  db:
    # image for our postgreSQL retrieval at https://hub.docker.com/_/postgres/tags?page=1&name=13-alpine
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/.postgresql/data
    # env data to set initial db configuration
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
