---
name: Checks

# The job trigger is push
on: [push]

# Define new job named test-lint
jobs:
  test-lint:
    name: Test and Lint
    # Runner - Check github actions documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # uses another pre-made action provided for github actions
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # Checkout our code to run tests and lint
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
